// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenServiceClient interface {
	CreateOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
	WriteOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
	ReadOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
	DropOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
	GetAllTokens(ctx context.Context, in *Token, opts ...grpc.CallOption) (TokenService_GetAllTokensClient, error)
}

type tokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenServiceClient(cc grpc.ClientConnInterface) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) CreateOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/token.TokenService/CreateOneToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) WriteOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/token.TokenService/WriteOneToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) ReadOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/token.TokenService/ReadOneToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) DropOneToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/token.TokenService/DropOneToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) GetAllTokens(ctx context.Context, in *Token, opts ...grpc.CallOption) (TokenService_GetAllTokensClient, error) {
	stream, err := c.cc.NewStream(ctx, &TokenService_ServiceDesc.Streams[0], "/token.TokenService/GetAllTokens", opts...)
	if err != nil {
		return nil, err
	}
	x := &tokenServiceGetAllTokensClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TokenService_GetAllTokensClient interface {
	Recv() (*Token, error)
	grpc.ClientStream
}

type tokenServiceGetAllTokensClient struct {
	grpc.ClientStream
}

func (x *tokenServiceGetAllTokensClient) Recv() (*Token, error) {
	m := new(Token)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TokenServiceServer is the server API for TokenService service.
// All implementations must embed UnimplementedTokenServiceServer
// for forward compatibility
type TokenServiceServer interface {
	CreateOneToken(context.Context, *Token) (*Token, error)
	WriteOneToken(context.Context, *Token) (*Token, error)
	ReadOneToken(context.Context, *Token) (*Token, error)
	DropOneToken(context.Context, *Token) (*Token, error)
	GetAllTokens(*Token, TokenService_GetAllTokensServer) error
	mustEmbedUnimplementedTokenServiceServer()
}

// UnimplementedTokenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTokenServiceServer struct {
}

func (UnimplementedTokenServiceServer) CreateOneToken(context.Context, *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOneToken not implemented")
}
func (UnimplementedTokenServiceServer) WriteOneToken(context.Context, *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteOneToken not implemented")
}
func (UnimplementedTokenServiceServer) ReadOneToken(context.Context, *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOneToken not implemented")
}
func (UnimplementedTokenServiceServer) DropOneToken(context.Context, *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropOneToken not implemented")
}
func (UnimplementedTokenServiceServer) GetAllTokens(*Token, TokenService_GetAllTokensServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllTokens not implemented")
}
func (UnimplementedTokenServiceServer) mustEmbedUnimplementedTokenServiceServer() {}

// UnsafeTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServiceServer will
// result in compilation errors.
type UnsafeTokenServiceServer interface {
	mustEmbedUnimplementedTokenServiceServer()
}

func RegisterTokenServiceServer(s grpc.ServiceRegistrar, srv TokenServiceServer) {
	s.RegisterService(&TokenService_ServiceDesc, srv)
}

func _TokenService_CreateOneToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).CreateOneToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.TokenService/CreateOneToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).CreateOneToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_WriteOneToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).WriteOneToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.TokenService/WriteOneToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).WriteOneToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_ReadOneToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).ReadOneToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.TokenService/ReadOneToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).ReadOneToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_DropOneToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).DropOneToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.TokenService/DropOneToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).DropOneToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_GetAllTokens_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Token)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TokenServiceServer).GetAllTokens(m, &tokenServiceGetAllTokensServer{stream})
}

type TokenService_GetAllTokensServer interface {
	Send(*Token) error
	grpc.ServerStream
}

type tokenServiceGetAllTokensServer struct {
	grpc.ServerStream
}

func (x *tokenServiceGetAllTokensServer) Send(m *Token) error {
	return x.ServerStream.SendMsg(m)
}

// TokenService_ServiceDesc is the grpc.ServiceDesc for TokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "token.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOneToken",
			Handler:    _TokenService_CreateOneToken_Handler,
		},
		{
			MethodName: "WriteOneToken",
			Handler:    _TokenService_WriteOneToken_Handler,
		},
		{
			MethodName: "ReadOneToken",
			Handler:    _TokenService_ReadOneToken_Handler,
		},
		{
			MethodName: "DropOneToken",
			Handler:    _TokenService_DropOneToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllTokens",
			Handler:       _TokenService_GetAllTokens_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "token/token.proto",
}
